### ISSUE TITLE
HTTP 500 when accessing OpenRefine

### ISSUE THREAD

**Issue by tumbak** [sparkica/dbpedia-extension#1]
Hello,

I tried installing the extension against a clean clone of OpenRefines's git repository, I added the build and clean section to build.xml as instructed, refine starts correctly but when trying to access and page it gives the following

``` bash
Problem accessing /project. Reason:

    Butterfly Error
Butterfly incurred in the following errors while initializing:
java.lang.Exception: Failed to initialize module dbpedia-extension [edu.mit.simile.butterfly.ButterflyModuleImpl]
    at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:478)
    at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
    at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
    at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
    at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
    at com.google.refine.RefineServer.configure(Refine.java:286)
    at com.google.refine.RefineServer.init(Refine.java:200)
    at com.google.refine.Refine.init(Refine.java:113)
    at com.google.refine.Refine.main(Refine.java:107)
Caused by: org.mozilla.javascript.EvaluatorException: Can't find method com.google.refine.RefineServlet.cacheClass(object). (file:/Users/zaid/Sites/OpenRefine/main/webapp/../../extensions/dbpedia-extension/module/MOD-INF/controller.js#64)
    at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:109)
    at org.mozilla.javascript.Context.reportRuntimeError(Context.java:938)
    at org.mozilla.javascript.Context.reportRuntimeError(Context.java:994)
    at org.mozilla.javascript.Context.reportRuntimeError1(Context.java:957)
    at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:166)
    at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
    at org.mozilla.javascript.gen.c6._c1(file:/Users/zaid/Sites/OpenRefine/main/webapp/../../extensions/dbpedia-extension/module/MOD-INF/controller.js:64)
    at org.mozilla.javascript.gen.c6.call(file:/Users/zaid/Sites/OpenRefine/main/webapp/../../extensions/dbpedia-extension/module/MOD-INF/controller.js)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:398)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3065)
    at org.mozilla.javascript.gen.c6.call(file:/Users/zaid/Sites/OpenRefine/main/webapp/../../extensions/dbpedia-extension/module/MOD-INF/controller.js)
    at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636)
    at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
    at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
    ... 8 more
```

I'd fix it myself but I'm a java noob, got any hints?

**Comment by sparkica** [comment]
You have to build the extension, because this repository doesn't include binary files. 
In terminal go to the OpenRefine folder and type: 
     ./refine clean

to remove existing binary files and then build sources with:
     ./refine build

When it's done, you can run it by typing: 
     ./refine

Btw. to use DBpedia extension you'll need grefine-rdf-extension, which might cause some problems when building from source. I suggest you download and try LODRefine (https://github.com/sparkica/OpenRefine). LODRefine is a fork of OpenRefine repo and it includes all the extensions you might need (rdf-extension, dbpedia-extension, stats-extension)...

**Comment by tumbak** [comment]
Thank you, the fork you mentioned has everything, will give it a try
