### ISSUE TITLE
HTTP 500: Can't find method com.google.refine.RefineServlet.cacheClass(object)

### ISSUE THREAD

**Issue by timrdf** [sparkica/dbpedia-extension#4]
Using Google Refine 2.5 (and 2.0) Mac binary, and installing dbpedia-extension at `/Users/me/Library/Application Support/Google/Refine/extensions` with `git clone https://github.com/sparkica/dbpedia-extension.git`, loading http://localhost:3333/ reported:

```
HTTP ERROR 500

Problem accessing /. Reason:

    Butterfly Error
Butterfly incurred in the following errors while initializing:
java.lang.Exception: Failed to initialize module dbpedia-extension [edu.mit.simile.butterfly.ButterflyModuleImpl]
    at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:478)
    at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
    at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
    at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
    at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
    at com.google.refine.RefineServer.configure(Refine.java:284)
    at com.google.refine.RefineServer.init(Refine.java:198)
    at com.google.refine.Refine.init(Refine.java:113)
    at com.google.refine.Refine.main(Refine.java:107)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at apple.launcher.LaunchRunner.run(LaunchRunner.java:116)
    at apple.launcher.LaunchRunner.callMain(LaunchRunner.java:51)
    at apple.launcher.JavaApplicationLauncher.launch(JavaApplicationLauncher.java:52)
Caused by: org.mozilla.javascript.EvaluatorException: Can't find method com.google.refine.RefineServlet.cacheClass(object). (file:/Users/me/Library/Application%20Support/Google/Refine/extensions/dbpedia-extension/module/MOD-INF/controller.js#62)
    at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:109)
    at org.mozilla.javascript.Context.reportRuntimeError(Context.java:938)
    at org.mozilla.javascript.Context.reportRuntimeError(Context.java:994)
    at org.mozilla.javascript.Context.reportRuntimeError1(Context.java:957)
    at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:166)
    at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
    at org.mozilla.javascript.gen.c4._c1(file:/Users/me/Library/Application%20Support/Google/Refine/extensions/dbpedia-extension/module/MOD-INF/controller.js:62)
    at org.mozilla.javascript.gen.c4.call(file:/Users/me/Library/Application%20Support/Google/Refine/extensions/dbpedia-extension/module/MOD-INF/controller.js)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:398)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3065)
    at org.mozilla.javascript.gen.c4.call(file:/Users/me/Library/Application%20Support/Google/Refine/extensions/dbpedia-extension/module/MOD-INF/controller.js)
    at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636)
    at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
    at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
    ... 15 more
```

**Comment by sefradama** [comment]
I got same error with OpenRefine on linux but resolved by running 'ant' from openrefine directory

**Comment by danpaulsmith** [comment]
I'm getting this with OpenRefine 2.6 rc2

**Comment by sparkica** [comment]
@danpaulsmith I haven't been working on this extension for a while now... I'm not sure the extension even works with v2.6, because afaik they changed a lot of things... Have you tried the solution @goonbag suggested? I'll try to look into this issue as soon as I can, but I can promise anything.
